### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dragens-dev** [0Kee-Team/CatchMail#3]
Hello. When I tried to run your program, it gave out a lot of errors. How do I fix it?
![Снимок](https://user-images.githubusercontent.com/61161964/74681817-b4782a00-5157-11ea-8f3c-2415d6bc6e88.PNG)

**Comment by lilololi** [comment]
change line 46 "res = requests.post(url=__URL__,data= payload,verify=False)"

Add “,verify=False” to solve the problem。
